<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <formFactors>Large</formFactors>
    <label>Vlocity Telecommunication Services</label>
    <logo>VlocityCMTResources/CommuincationMediaAndTechnologyLogo.gif</logo>
    <tab>standard-Contact</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Account</tab>
    <tab>standard-Order</tab>
    <tab>standard-report</tab>
    <tab>DataRaptor</tab>
    <tab>Household__c</tab>
    <tab>Interface_DRGeneric__c</tab>
    <tab>PartyRelationshipType__c</tab>
    <tab>AccountBalance__c</tab>
    <tab>EntityFilter__c</tab>
    <tab>FieldMapper</tab>
    <tab>InterfaceImplementation__c</tab>
    <tab>PaymentAdjustment__c</tab>
    <tab>PaymentMethod__c</tab>
    <tab>ProductEligibility__c</tab>
    <tab>ProductRelationship__c</tab>
    <tab>Statement__c</tab>
    <tab>CMTAdmin</tab>
    <tab>Vlocity_Rule_Workbench</tab>
    <tab>OfferingProcedure__c</tab>
    <tab>Contact_Motive__c</tab>
    <tab>Location__c</tab>
    <tab>Case_Resolution_Time__c</tab>
    <tab>Case_Channel_Configuration__c</tab>
    <tab>TaxCondition__c</tab>
    <tab>TaxConditionDetail__c</tab>
    <tab>ObjectClass__c</tab>
    <tab>ObjectLayout__c</tab>
    <tab>AttributeAssignment__c</tab>
    <tab>BusinessSite__c</tab>
    <tab>PromotionItem__c</tab>
    <tab>PricingElement__c</tab>
    <tab>DecompositionRelationship__c</tab>
    <tab>PriceList__c</tab>
    <tab>PriceListEntry__c</tab>
    <tab>Datastore__c</tab>
    <tab>Crossobject__c</tab>
    <tab>VlocityTrackingEntry__c</tab>
    <tab>Transaction_History__c</tab>
    <tab>ReglasGestorPuntos</tab>
    <tab>FinancialPromotion__c</tab>
    <tab>GP_Atributo_de_una_transaccion__c</tab>
    <tab>GP_Socio__c</tab>
    <tab>Work_Team_Permission__c</tab>
    <tab>InboundRESTInterface__c</tab>
    <tab>DRAsset__c</tab>
    <tab>Work_Team_Management</tab>
    <tab>Address2__c</tab>
    <tab>ManageMyWorkTeams</tab>
    <tab>ManageCrossTeamMembers</tab>
    <tab>SyncDeltaObject__c</tab>
    <tab>Mantenimiento_de_Eventos</tab>
    <tab>GP_Evento_General__c</tab>
    <tab>Permissions_by_workteam</tab>
</CustomApplication>
