<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <customApplicationComponents>
        <alignment>right</alignment>
        <customApplicationComponent>LookupComponent</customApplicationComponent>
    </customApplicationComponents>
    <defaultLandingTab>standard-home</defaultLandingTab>
    <detailPageRefreshMethod>none</detailPageRefreshMethod>
    <enableCustomizeMyTabs>false</enableCustomizeMyTabs>
    <enableKeyboardShortcuts>true</enableKeyboardShortcuts>
    <enableListViewHover>true</enableListViewHover>
    <enableListViewReskin>true</enableListViewReskin>
    <enableMultiMonitorComponents>true</enableMultiMonitorComponents>
    <enablePinTabs>true</enablePinTabs>
    <enableTabHover>false</enableTabHover>
    <enableTabLimits>false</enableTabLimits>
    <headerColor>#FFFFFF</headerColor>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <keyboardShortcuts>
        <defaultShortcut>
            <action>FOCUS_CONSOLE</action>
            <active>true</active>
            <keyCommand>ESC</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_NAVIGATOR_TAB</action>
            <active>true</active>
            <keyCommand>V</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_DETAIL_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_PRIMARY_TAB_PANEL</action>
            <active>true</active>
            <keyCommand>P</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SUBTAB_PANEL</action>
            <active>true</active>
            <keyCommand>S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FIRST_LIST_VIEW</action>
            <active>true</active>
            <keyCommand>SHIFT+F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_SEARCH_INPUT</action>
            <active>true</active>
            <keyCommand>R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_LEFT</action>
            <active>true</active>
            <keyCommand>LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>MOVE_RIGHT</action>
            <active>true</active>
            <keyCommand>RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>UP_ARROW</action>
            <active>true</active>
            <keyCommand>UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>DOWN_ARROW</action>
            <active>true</active>
            <keyCommand>DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB_SCROLLER_MENU</action>
            <active>true</active>
            <keyCommand>D</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>OPEN_TAB</action>
            <active>true</active>
            <keyCommand>T</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CLOSE_TAB</action>
            <active>true</active>
            <keyCommand>C</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REFRESH_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+R</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>ENTER</action>
            <active>true</active>
            <keyCommand>ENTER</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>EDIT</action>
            <active>true</active>
            <keyCommand>E</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>SAVE</action>
            <active>true</active>
            <keyCommand>CTRL+S</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>CONSOLE_LINK_DIALOG</action>
            <active>false</active>
            <keyCommand>U</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>HOTKEYS_PANEL</action>
            <active>false</active>
            <keyCommand>SHIFT+K</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_MACRO</action>
            <active>false</active>
            <keyCommand>M</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>FOCUS_FOOTER_PANEL</action>
            <active>false</active>
            <keyCommand>F</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LIST_VIEW</action>
            <active>false</active>
            <keyCommand>SHIFT+N</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_LEFT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+LEFT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_RIGHT_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+RIGHT ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_TOP_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+UP ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_BOTTOM_SIDEBAR</action>
            <active>false</active>
            <keyCommand>SHIFT+DOWN ARROW</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>TOGGLE_APP_LEVEL_COMPONENTS</action>
            <active>false</active>
            <keyCommand>Z</keyCommand>
        </defaultShortcut>
        <defaultShortcut>
            <action>REOPEN_LAST_TAB</action>
            <active>false</active>
            <keyCommand>SHIFT+C</keyCommand>
        </defaultShortcut>
    </keyboardShortcuts>
    <label>Vlocity Console Application</label>
    <listPlacement>
        <location>full</location>
    </listPlacement>
    <listRefreshMethod>none</listRefreshMethod>
    <primaryTabColor>#0070D2</primaryTabColor>
    <saveUserSessions>true</saveUserSessions>
    <tab>standard-Case</tab>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Opportunity</tab>
    <tab>CustomerInteraction__c</tab>
    <tab>Contact_Motive__c</tab>
    <tab>Location__c</tab>
    <tab>Case_Resolution_Time__c</tab>
    <tab>Case_Channel_Configuration__c</tab>
    <tab>ObjectClass__c</tab>
    <tab>ObjectLayout__c</tab>
    <tab>AttributeAssignment__c</tab>
    <tab>BusinessSite__c</tab>
    <tab>PromotionItem__c</tab>
    <tab>PricingElement__c</tab>
    <tab>DecompositionRelationship__c</tab>
    <tab>PriceList__c</tab>
    <tab>PriceListEntry__c</tab>
    <tab>Datastore__c</tab>
    <tab>Crossobject__c</tab>
    <tab>VlocityTrackingEntry__c</tab>
    <tab>Transaction_History__c</tab>
    <tab>ReglasGestorPuntos</tab>
    <tab>FinancialPromotion__c</tab>
    <tab>GP_Atributo_de_una_transaccion__c</tab>
    <tab>GP_Socio__c</tab>
    <tab>Work_Team_Permission__c</tab>
    <tab>InboundRESTInterface__c</tab>
    <tab>DRAsset__c</tab>
    <tab>Work_Team_Management</tab>
    <tab>Address2__c</tab>
    <tab>ManageMyWorkTeams</tab>
    <tab>ManageCrossTeamMembers</tab>
    <tab>SyncDeltaObject__c</tab>
    <tab>Mantenimiento_de_Eventos</tab>
    <tab>GP_Evento_General__c</tab>
    <tab>Permissions_by_workteam</tab>
    <workspaceMappings>
        <mapping>
            <tab>Address2__c</tab>
        </mapping>
        <mapping>
            <tab>AttributeAssignment__c</tab>
        </mapping>
        <mapping>
            <tab>BusinessSite__c</tab>
        </mapping>
        <mapping>
            <tab>Case_Channel_Configuration__c</tab>
        </mapping>
        <mapping>
            <tab>Case_Resolution_Time__c</tab>
        </mapping>
        <mapping>
            <tab>Contact_Motive__c</tab>
        </mapping>
        <mapping>
            <tab>Crossobject__c</tab>
        </mapping>
        <mapping>
            <tab>CustomerInteraction__c</tab>
        </mapping>
        <mapping>
            <tab>DRAsset__c</tab>
        </mapping>
        <mapping>
            <tab>Datastore__c</tab>
        </mapping>
        <mapping>
            <tab>DecompositionRelationship__c</tab>
        </mapping>
        <mapping>
            <tab>FinancialPromotion__c</tab>
        </mapping>
        <mapping>
            <tab>GP_Atributo_de_una_transaccion__c</tab>
        </mapping>
        <mapping>
            <tab>GP_Evento_General__c</tab>
        </mapping>
        <mapping>
            <tab>GP_Socio__c</tab>
        </mapping>
        <mapping>
            <tab>InboundRESTInterface__c</tab>
        </mapping>
        <mapping>
            <tab>Location__c</tab>
        </mapping>
        <mapping>
            <tab>ManageCrossTeamMembers</tab>
        </mapping>
        <mapping>
            <tab>ManageMyWorkTeams</tab>
        </mapping>
        <mapping>
            <tab>Mantenimiento_de_Eventos</tab>
        </mapping>
        <mapping>
            <tab>ObjectClass__c</tab>
        </mapping>
        <mapping>
            <tab>ObjectLayout__c</tab>
        </mapping>
        <mapping>
            <tab>Permissions_by_workteam</tab>
        </mapping>
        <mapping>
            <tab>PriceListEntry__c</tab>
        </mapping>
        <mapping>
            <tab>PriceList__c</tab>
        </mapping>
        <mapping>
            <tab>PricingElement__c</tab>
        </mapping>
        <mapping>
            <tab>PromotionItem__c</tab>
        </mapping>
        <mapping>
            <tab>ReglasGestorPuntos</tab>
        </mapping>
        <mapping>
            <tab>SyncDeltaObject__c</tab>
        </mapping>
        <mapping>
            <tab>Transaction_History__c</tab>
        </mapping>
        <mapping>
            <tab>VlocityTrackingEntry__c</tab>
        </mapping>
        <mapping>
            <tab>Work_Team_Management</tab>
        </mapping>
        <mapping>
            <tab>Work_Team_Permission__c</tab>
        </mapping>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <tab>standard-Contact</tab>
        </mapping>
        <mapping>
            <tab>standard-Lead</tab>
        </mapping>
        <mapping>
            <tab>standard-Opportunity</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
