<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <formFactors>Large</formFactors>
    <label>SCP</label>
    <logo>SCP/LogoTelecom.png</logo>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Opportunity</tab>
    <tab>SCP</tab>
    <tab>standard-report</tab>
    <tab>Dollar_Budget</tab>
    <tab>vlocity_cmt__VlocityTrackingEntry__c</tab>
    <tab>Transaction_History__c</tab>
    <tab>ReglasGestorPuntos</tab>
    <tab>FinancialPromotion__c</tab>
    <tab>GP_Atributo_de_una_transaccion__c</tab>
    <tab>GP_Socio__c</tab>
    <tab>Work_Team_Permission__c</tab>
    <tab>vlocity_cmt__InboundRESTInterface__c</tab>
    <tab>DRAsset__c</tab>
    <tab>Work_Team_Management</tab>
    <tab>Address2__c</tab>
    <tab>ManageMyWorkTeams</tab>
    <tab>ManageCrossTeamMembers</tab>
    <tab>vlocity_cmt__SyncDeltaObject__c</tab>
    <tab>Mantenimiento_de_Eventos</tab>
    <tab>GP_Evento_General__c</tab>
    <tab>Permissions_by_workteam</tab>
</CustomApplication>
